# Generated by Django 5.1.4 on 2025-01-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_changed',
            field=models.BooleanField(default=False),
        ),
    ]
