# Generated by Django 5.1.4 on 2025-01-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_order_status_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
